services:
  db:
    container_name: go-poc
    image: postgres:16
    environment:
      - POSTGRES_DB=go-poc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: {}
  